services:
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:mysecretpassword@db:5432/your_app_development"
    #   - RAILS_ENV=test
    env_file: ".env"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres       # Default: 'postgres' if not set
      POSTGRES_PASSWORD: mysecretpassword   # Required if POSTGRES_USER is set
      POSTGRES_DB: POSTGRES_USER  # Optional (defaults to POSTGRES_USER)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
secrets:
  db-password:
    file: db/password.txt