default: &default
  adapter: postgresql
  encoding: unicode
  host: db  # Must match the PostgreSQL service name in docker-compose.yml
  username: <%= ENV["POSTGRES_USER"] %>  # Same as POSTGRES_USER
  password: <%= ENV["POSTGRES_PASSWORD"] %>  # Same as POSTGRES_PASSWORD
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_app_development  # Same as POSTGRES_DB (or defaults to username)

test:
  <<: *default
  database: your_app_test